# Generated by Django 4.0.1 on 2022-06-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_blogitem_date_blogitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogitem',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
