# Generated by Django 4.0.1 on 2022-07-12 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_blogitem_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('comment', models.CharField(default='', max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(default='', max_length=100)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.blogitem')),
            ],
        ),
    ]
