# Generated by Django 4.0 on 2022-07-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_blogauthor_blogitem_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='image',
            field=models.ImageField(default='', upload_to='images/author'),
        ),
    ]
