# Generated by Django 4.0 on 2022-07-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_commentitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentitem',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
