# Generated by Django 4.0 on 2022-07-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_blogitem_commentcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='instagram_id',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='twitter_id',
            field=models.TextField(default='', max_length=500),
        ),
    ]
