# Generated by Django 4.0.6 on 2022-07-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_blogauthor_instagram_id_blogauthor_twitter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='instagram_id',
            field=models.TextField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='twitter_id',
            field=models.TextField(default='', max_length=90),
        ),
    ]
